INSERT INTO menu_items (price, name, description)
VALUES (9.99, 'Margherita Pizza', 'Klassieke pizza met tomaat, mozzarella en basilicum'),
       (11.49, 'Pepperoni Pizza', 'Tomaat, mozzarella en pepperoni'),
       (12.99, 'BBQ Kip Pizza', 'Gegrilde kip, BBQ-saus, rode ui en kaas'),
       (10.49, 'Veggie Burger', 'Plantaardige burger met sla, tomaat en ui'),
       (9.49, 'Cheeseburger', 'Rundvleesburger met cheddar, sla, tomaat en augurken'),
       (13.49, 'Double Bacon Burger', 'Twee runderburgers met bacon en cheddar'),
       (8.49, 'Caesar Salade', 'Romeinse sla, parmezaan, croutons en caesardressing'),
       (8.99, 'Griekse Salade', 'Komkommer, tomaat, olijven, feta en vinaigrette'),
       (9.99, 'Kip Wrap', 'Gegrilde kip, gemengde sla en knoflookmayonaise in een wrap'),
       (9.49, 'Falafel Wrap', 'Falafel, hummus en verse groenten in platbrood'),
       (12.49, 'Spaghetti Bolognese', 'Pasta met rijke runder- en tomatensaus'),
       (11.99, 'Penne Alfredo', 'Penne pasta in romige Alfredo-saus'),
       (6.49, 'Tomatensoep', 'Romige geroosterde tomatensoep met kruiden'),
       (6.99, 'Champignonsoep', 'Fluweelachtige champignonsoep met knoflook en tijm'),
       (3.99, 'Frietjes', 'Knapperige goudgekleurde aardappelfrietjes'),
       (4.49, 'Uienringen', 'Gefrituurde uienringen met dipsaus'),
       (5.49, 'Chocolade Brownie', 'Warme brownie met chocoladesaus'),
       (5.99, 'Cheesecake stuk', 'Klassiek gebakken cheesecake stuk'),
       (2.99, 'Limonade', 'Vers gemaakte limonade'),
       (2.79, 'Iced Tea', 'Gekoelde zwarte thee met citroen');